-- Clear existing universities to avoid duplicates and mixed languages
DELETE FROM public.universities; 

-- Insert Real Universities (Massive Batch)
INSERT INTO public.universities (name, slug, country, city, cost_description, ielts_score, flag_emoji, scholarship_info, image_url, details_json)
VALUES 
-- ==========================================
-- USA & Canada
-- ==========================================
('Harvard University', 'harvard-university', 'США', 'Кембридж', 'от $54,000 / год', 7.5, '🇺🇸', 'Need-based financial aid', 'https://images.unsplash.com/photo-1559135197-8a45ea74d367?q=80&w=1000&auto=format&fit=crop', '{"website": "https://harvard.edu", "description": "Один из самых престижных университетов мира, член Лиги плюща."}'),
('Stanford University', 'stanford-university', 'США', 'Стэнфорд', 'от $56,000 / год', 7.0, '🇺🇸', 'Merit & Need-based aid', 'https://images.unsplash.com/photo-1623000850262-637992994647?q=80&w=1000&auto=format&fit=crop', '{"website": "https://stanford.edu", "description": "Ведущий исследовательский университет в сердце Кремниевой долины."}'),
('MIT', 'mit', 'США', 'Кембридж', 'от $57,000 / год', 7.5, '🇺🇸', 'Need-blind admission', 'https://images.unsplash.com/photo-1564981797816-1043664bf78d?q=80&w=1000&auto=format&fit=crop', '{"website": "https://mit.edu", "description": "Мировой лидер в области точных наук и инженерии."}'),
('Yale University', 'yale-university', 'США', 'Нью-Хейвен', 'от $55,000 / год', 7.5, '🇺🇸', 'Need-based grants', 'https://images.unsplash.com/photo-1582649066601-5256597e3077?q=80&w=1000&auto=format&fit=crop', '{"website": "https://yale.edu", "description": "Один из старейших университетов США, известен своими гуманитарными программами."}'),
('Princeton University', 'princeton-university', 'США', 'Принстон', 'от $53,000 / год', 7.5, '🇺🇸', 'Need-blind for all', 'https://images.unsplash.com/photo-1623944893558-2de5a55389d6?q=80&w=1000&auto=format&fit=crop', '{"website": "https://princeton.edu", "description": "Фокус на бакалавриате и исследованиях. Прекрасный кампус."}'),
('University of Toronto', 'utoronto', 'Канада', 'Торонто', 'от CAD 60,000 / год', 6.5, '🇨🇦', 'Lester B. Pearson', 'https://images.unsplash.com/photo-1617575521317-d2974f3b56d2?q=80&w=1000&auto=format&fit=crop', '{"website": "https://utoronto.ca", "description": "Ведущий вуз Канады. Расположен в центре одного из самых безопасных мегаполисов мира."}'),
('UBC', 'ubc', 'Канада', 'Ванкувер', 'от CAD 45,000 / год', 6.5, '🇨🇦', 'International Scholars', 'https://images.unsplash.com/photo-1564356467-333333333333?q=80&w=1000&auto=format&fit=crop', '{"website": "https://ubc.ca", "description": "Университет Британской Колумбии. Потрясающая природа и сильные науки."}'),

-- ==========================================
-- UK & Europe
-- ==========================================
('University of Oxford', 'university-of-oxford', 'Великобритания', 'Оксфорд', 'от £28,000 / год', 7.5, '🇬🇧', 'Rhodes Scholarship', 'https://images.unsplash.com/photo-1580843411760-d38764023e5c?q=80&w=1000&auto=format&fit=crop', '{"website": "https://ox.ac.uk", "description": "Старейший университет в англоязычном мире."}'),
('University of Cambridge', 'university-of-cambridge', 'Великобритания', 'Кембридж', 'от £30,000 / год', 7.5, '🇬🇧', 'Gates Cambridge', 'https://images.unsplash.com/photo-1492318041721-75294158223d?q=80&w=1000&auto=format&fit=crop', '{"website": "https://cam.ac.uk", "description": "Один из самых известных университетов мира."}'),
('Imperial College London', 'imperial-college-london', 'Великобритания', 'Лондон', 'от £34,000 / год', 7.0, '🇬🇧', 'President''s Scholarship', 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=1000&auto=format&fit=crop', '{"website": "https://imperial.ac.uk", "description": "Наука, инженерия, медицина и бизнес."}'),
('ETH Zurich', 'eth-zurich', 'Швейцария', 'Цюрих', 'от 1,500 CHF / год', 6.5, '🇨🇭', 'Excellence Scholarship', 'https://images.unsplash.com/photo-1521133573892-e44906baee46?q=80&w=1000&auto=format&fit=crop', '{"website": "https://ethz.ch", "description": "Ведущий технический вуз Европы. Альма-матер Эйнштейна."}'),
('Technical University of Munich', 'tum', 'Германия', 'Мюнхен', 'Бесплатно (сборы)', 6.5, '🇩🇪', 'DAAD Scholarships', 'https://images.unsplash.com/photo-1590248430259-5298072bc85c?q=80&w=1000&auto=format&fit=crop', '{"website": "https://tum.de", "description": "Лучший технический университет Германии."}'),
('University of Amsterdam', 'uva', 'Нидерланды', 'Амстердам', 'от €12,000 / год', 6.5, '🇳🇱', 'Amsterdam Merit', 'https://images.unsplash.com/photo-1466096115517-bceecbfb6fde?q=80&w=1000&auto=format&fit=crop', '{"website": "https://uva.nl", "description": "Современный университет в креативном центре Европы."}'),
('Sorbonne University', 'sorbonne', 'Франция', 'Париж', 'от €3,000 / год', 6.5, '🇫🇷', 'Eiffel Scholarship', 'https://images.unsplash.com/photo-1499856871940-a09627c6d7db?q=80&w=1000&auto=format&fit=crop', '{"website": "https://sorbonne-universite.fr", "description": "Легендарный университет в сердце Парижа."}'),
('Bocconi University', 'bocconi', 'Италия', 'Милан', 'от €14,000 / год', 6.5, '🇮🇹', 'Bocconi Merit Award', 'https://images.unsplash.com/photo-1551189671-d68b6356d40c?q=80&w=1000&auto=format&fit=crop', '{"website": "https://unibocconi.eu", "description": "Топовый бизнес-вуз Европы."}'),

-- ==========================================
-- Eastern Europe (Popular for KZ)
-- ==========================================
('Charles University', 'charles-university', 'Чехия', 'Прага', 'Бесплатно (на чешском)', 6.0, '🇨🇿', 'Government Grants', 'https://images.unsplash.com/photo-1592912364893-b6644a55e4b1?q=80&w=1000&auto=format&fit=crop', '{"website": "https://cuni.cz", "description": "Старейший университет Центральной Европы."}'),
('Masaryk University', 'masaryk-university', 'Чехия', 'Брно', 'Бесплатно (на чешском)', 6.0, '🇨🇿', 'University Grants', 'https://images.unsplash.com/photo-1565058688-69f37c35d58d?q=80&w=1000&auto=format&fit=crop', '{"website": "https://muni.cz", "description": "Второй по величине вуз Чехии, современный кампус."}'),
('University of Warsaw', 'university-of-warsaw', 'Польша', 'Варшава', 'от €2,000 / год', 6.0, '🇵🇱', 'Government Scholarship', 'https://images.unsplash.com/photo-1590012314607-cda9d9b699ae?q=80&w=1000&auto=format&fit=crop', '{"website": "https://en.uw.edu.pl", "description": "Крупнейший вуз Польши."}'),
('Jagiellonian University', 'jagiellonian-university', 'Польша', 'Краков', 'от €2,500 / год', 6.0, '🇵🇱', 'NAWA Scholarship', 'https://images.unsplash.com/photo-1519112232436-9923c63be930?q=80&w=1000&auto=format&fit=crop', '{"website": "https://en.uj.edu.pl", "description": "Один из старейших университетов Европы."}'),
('University of Debrecen', 'university-of-debrecen', 'Венгрия', 'Дебрецен', 'Stipendium Hungaricum', 5.5, '🇭🇺', 'Full Scholarship', 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?q=80&w=1000&auto=format&fit=crop', '{"website": "https://unideb.hu", "description": "Популярный выбор для медицины и инженерии."}'),
('Corvinus University', 'corvinus-university', 'Венгрия', 'Будапешт', 'Stipendium Hungaricum', 6.0, '🇭🇺', 'Full Scholarship', 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?q=80&w=1000&auto=format&fit=crop', '{"website": "https://uni-corvinus.hu", "description": "Ведущий экономический вуз Венгрии."}'),

-- ==========================================
-- Turkey (Very Popular)
-- ==========================================
('Koc University', 'koc-university', 'Турция', 'Стамбул', 'от $20,000 / год', 6.0, '🇹🇷', 'Full Merit Scholarship', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=1000&auto=format&fit=crop', '{"website": "https://ku.edu.tr", "description": "Лучший частный университет Турции. Обучение на английском."}'),
('Sabanci University', 'sabanci-university', 'Турция', 'Стамбул', 'от $18,000 / год', 6.0, '🇹🇷', 'Tuition Waiver', 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=1000&auto=format&fit=crop', '{"website": "https://sabanciuniv.edu", "description": "Инновационный университет с гибкой системой выбора специальности."}'),
('Bilkent University', 'bilkent-university', 'Турция', 'Анкара', 'от $14,000 / год', 6.0, '🇹🇷', 'Merit Scholarship', 'https://images.unsplash.com/photo-1595113316349-9fa4eb24f884?q=80&w=1000&auto=format&fit=crop', '{"website": "https://bilkent.edu.tr", "description": "Первый частный университет Турции, высокие академические стандарты."}'),
('METU', 'metu', 'Турция', 'Анкара', 'от $1,000 / год', 6.0, '🇹🇷', 'Government Grants', 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=1000&auto=format&fit=crop', '{"website": "https://metu.edu.tr", "description": "Middle East Technical University. Лидер в инженерии."}'),
('Istanbul Technical University', 'itu', 'Турция', 'Стамбул', 'от $1,500 / год', 6.0, '🇹🇷', 'Turkiye Burslari', 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=1000&auto=format&fit=crop', '{"website": "https://itu.edu.tr", "description": "Один из старейших технических вузов мира."}'),

-- ==========================================
-- Asia
-- ==========================================
('National University of Singapore', 'nus', 'Сингапур', 'Сингапур', 'от S$30,000 / год', 6.5, '🇸🇬', 'ASEAN Scholarship', 'https://images.unsplash.com/photo-1558448831-29547d6d7926?q=80&w=1000&auto=format&fit=crop', '{"website": "https://nus.edu.sg", "description": "Лучший университет Азии."}'),
('NTU Singapore', 'ntu', 'Сингапур', 'Сингапур', 'от S$30,000 / год', 6.5, '🇸🇬', 'Nanyang Scholarship', 'https://images.unsplash.com/photo-1569974498991-d3c12a504f95?q=80&w=1000&auto=format&fit=crop', '{"website": "https://ntu.edu.sg", "description": "Огромный зеленый кампус и передовые технологии."}'),
('Tsinghua University', 'tsinghua', 'Китай', 'Пекин', 'от 30,000 RMB / год', 6.0, '🇨🇳', 'Chinese Gov Scholarship', 'https://images.unsplash.com/photo-1599583107053-02047243916d?q=80&w=1000&auto=format&fit=crop', '{"website": "https://tsinghua.edu.cn", "description": "Ведущий вуз Китая."}'),
('Peking University', 'peking-university', 'Китай', 'Пекин', 'от 30,000 RMB / год', 6.0, '🇨🇳', 'CGS', 'https://images.unsplash.com/photo-1583324113626-70df0f4deaab?q=80&w=1000&auto=format&fit=crop', '{"website": "https://pku.edu.cn", "description": "Старейший национальный университет Китая."}'),
('KAIST', 'kaist', 'Южная Корея', 'Тэджон', 'Грант 100%', 6.0, '🇰🇷', 'KAIST Scholarship', 'https://images.unsplash.com/photo-1589820296156-2454bb8a6d54?q=80&w=1000&auto=format&fit=crop', '{"website": "https://kaist.ac.kr", "description": "Главный научно-технический институт Кореи."}'),
('Seoul National University', 'snu', 'Южная Корея', 'Сеул', 'от $5,000 / год', 6.0, '🇰🇷', 'Global Korea Scholarship', 'https://images.unsplash.com/photo-1625244724120-1fd1d34d00f6?q=80&w=1000&auto=format&fit=crop', '{"website": "https://snu.ac.kr", "description": "Самый престижный вуз Кореи."}'),
('Yonsei University', 'yonsei', 'Южная Корея', 'Сеул', 'от $6,000 / год', 6.0, '🇰🇷', 'GKS / Underwood', 'https://images.unsplash.com/photo-1617135002202-0c3346b9a897?q=80&w=1000&auto=format&fit=crop', '{"website": "https://yonsei.ac.kr", "description": "Частный исследовательский университет, часть SKY."}'),
('Korea University', 'korea-university', 'Южная Корея', 'Сеул', 'от $6,000 / год', 6.0, '🇰🇷', 'KU Scholarship', 'https://images.unsplash.com/photo-1581368135153-a506cf13b1e1?q=80&w=1000&auto=format&fit=crop', '{"website": "https://korea.ac.kr", "description": "Один из трех лучших вузов страны."}'),
('University of Tokyo', 'university-of-tokyo', 'Япония', 'Токио', 'от $5,000 / год', 6.0, '🇯🇵', 'MEXT Scholarship', 'https://images.unsplash.com/photo-1572097662444-09c27208056b?q=80&w=1000&auto=format&fit=crop', '{"website": "https://u-tokyo.ac.jp", "description": "Самый престижный университет Японии."}'),
('Kyoto University', 'kyoto-university', 'Япония', 'Киото', 'от $5,000 / год', 6.0, '🇯🇵', 'MEXT', 'https://images.unsplash.com/photo-1528360983277-13d9b152c6d4?q=80&w=1000&auto=format&fit=crop', '{"website": "https://kyoto-u.ac.jp", "description": "Второй старейший университет Японии."}'),
('University of Hong Kong', 'hku', 'Гонконг', 'Гонконг', 'от HKD 170,000 / год', 6.5, '🇭🇰', 'Entrance Scholarship', 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?q=80&w=1000&auto=format&fit=crop', '{"website": "https://hku.hk", "description": "Старейший вуз Гонконга, глобальный центр исследований."}'),
('HKUST', 'hkust', 'Гонконг', 'Гонконг', 'от HKD 140,000 / год', 6.5, '🇭🇰', 'Redbird Scholarship', 'https://images.unsplash.com/photo-1516216628859-9bccecab13ca?q=80&w=1000&auto=format&fit=crop', '{"website": "https://hkust.edu.hk", "description": "Потрясающий кампус на берегу моря, сильный бизнес и инженерия."}'),

-- ==========================================
-- Australia
-- ==========================================
('University of Melbourne', 'unimelb', 'Австралия', 'Мельбурн', 'от AUD 40,000 / год', 6.5, '🇦🇺', 'Melbourne Intl Scholarship', 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?q=80&w=1000&auto=format&fit=crop', '{"website": "https://unimelb.edu.au", "description": "№1 в Австралии."}'),
('University of Sydney', 'usyd', 'Австралия', 'Сидней', 'от AUD 45,000 / год', 6.5, '🇦🇺', 'Vice-Chancellor''s', 'https://images.unsplash.com/photo-1596825205489-9ddc90f84945?q=80&w=1000&auto=format&fit=crop', '{"website": "https://sydney.edu.au", "description": "Первый университет Австралии."}'),
('UNSW Sydney', 'unsw', 'Австралия', 'Сидней', 'от AUD 42,000 / год', 6.5, '🇦🇺', 'International Scientia', 'https://images.unsplash.com/photo-1528642474493-227685b69b10?q=80&w=1000&auto=format&fit=crop', '{"website": "https://unsw.edu.au", "description": "Лидер в области технологий и предпринимательства."}'),
('Australian National University', 'anu', 'Австралия', 'Канберра', 'от AUD 39,000 / год', 6.5, '🇦🇺', 'Chancellor''s Scholarship', 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?q=80&w=1000&auto=format&fit=crop', '{"website": "https://anu.edu.au", "description": "Национальный университет в столице."}')

ON CONFLICT (slug) DO UPDATE SET 
    image_url = EXCLUDED.image_url,
    cost_description = EXCLUDED.cost_description,
    ielts_score = EXCLUDED.ielts_score,
    scholarship_info = EXCLUDED.scholarship_info,
    details_json = EXCLUDED.details_json;
